services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root  # Run Jenkins as root to access Docker socket
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  flask-app:
    image: flask-app
    container_name: flask-app
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - jenkins

volumes:
  jenkins_home:
    driver: local
